### PR TITLE
Summary

### PR DESCRIPTION
**Pull request by pnrobinson**

### CODE REVIEW

**Comment by pnrobinson** [comment]
Hi Luca -- nothing much to check here.. but we have a nice scale free distribution seen with the new script.

**Comment by LucaCappelletti94** [comment]
Hello Peter, I don't know what should I do here. I am not familiar with the script.

**Comment by pnrobinson** [comment]
Sorry Luca, it was an FYI and not a todo, I should have labeled better. I will merge for now.

**Comment by LucaCappelletti94** [comment]
Oh ok, thanks!

**Pull request merged**
